// Generated by scripts/build-drifters.py (do not edit by hand).
export type DrifterKind = "beacon" | "crystal" | "debris" | "needle" | "orb" | "probe" | "relay" | "rock" | "station" | "wreck";
export const DRIFTERS: { name: string; kind: DrifterKind; w: number; h: number }[] = [
  {
    name: "relay",
    kind: "relay",
    w: 237,
    h: 217
  },
  {
    name: "ring-station",
    kind: "station",
    w: 280,
    h: 218
  },
  {
    name: "dish-probe",
    kind: "probe",
    w: 256,
    h: 234
  },
  {
    name: "needle",
    kind: "needle",
    w: 106,
    h: 265
  },
  {
    name: "sputnik",
    kind: "probe",
    w: 240,
    h: 236
  },
  {
    name: "asteroid",
    kind: "rock",
    w: 237,
    h: 204
  },
  {
    name: "rock-cluster",
    kind: "debris",
    w: 266,
    h: 248
  },
  {
    name: "shard",
    kind: "rock",
    w: 215,
    h: 236
  },
  {
    name: "crystal-shard",
    kind: "crystal",
    w: 159,
    h: 284
  },
  {
    name: "debris-cluster",
    kind: "debris",
    w: 244,
    h: 220
  },
  {
    name: "beacon",
    kind: "beacon",
    w: 282,
    h: 262
  },
  {
    name: "cross-beacon",
    kind: "beacon",
    w: 282,
    h: 272
  },
  {
    name: "crystal",
    kind: "crystal",
    w: 164,
    h: 266
  },
  {
    name: "needle-2",
    kind: "needle",
    w: 115,
    h: 288
  },
  {
    name: "orb",
    kind: "orb",
    w: 262,
    h: 250
  },
  {
    name: "sphere-station",
    kind: "station",
    w: 166,
    h: 275
  },
  {
    name: "broken-ring",
    kind: "wreck",
    w: 277,
    h: 247
  },
  {
    name: "wreck",
    kind: "wreck",
    w: 283,
    h: 222
  }
];
