#!/usr/bin/env python3
"""Split the hero's meteor layers into individual rocks (for the pointer physics).

For each layer image in public/brand/, writes:
  public/brand/<name>-ids.png      rock ID per pixel (R = id & 255, G = id >> 8; 0 = none)
  public/brand/<name>-centres.png  each rock pixel's rock centre and whether it can move
and src/components/home/rocks.ts with each rock's centre and radius (source px).

Rocks are connected shapes in the alpha channel; each label is grown into the
soft fringe so a moved rock takes its edge with it.
Requires numpy, scipy and Pillow:  python3 scripts/build-rock-ids.py
"""
import json
import numpy as np
from PIL import Image
from scipy import ndimage

LAYERS = {"far": "meteors-far", "near": "meteors-near"}
out = {}
for key, name in LAYERS.items():
    rgba = np.asarray(Image.open(f"public/brand/{name}.webp").convert("RGBA"))
    a = rgba[..., 3]
    lab, count = ndimage.label(a > 25)
    sizes = ndimage.sum(np.ones_like(a), lab, range(1, count + 1))
    keep = np.zeros(count + 1, dtype=bool)
    keep[1:] = sizes >= 6
    lab = np.where(keep[lab], lab, 0)
    # Renumber 1..n
    ids = np.unique(lab[lab > 0])
    remap = np.zeros(count + 1, dtype=np.int32)
    remap[ids] = np.arange(1, len(ids) + 1)
    lab = remap[lab]
    # Grow labels into the soft fringe (alpha > 3, within 4 px).
    dist, (iy, ix) = ndimage.distance_transform_edt(lab == 0, return_indices=True)
    grown = lab[iy, ix]
    lab = np.where((lab == 0) & (a > 0) & (dist <= 7), grown, lab)
    n = int(lab.max())
    img = np.zeros((*lab.shape, 4), dtype=np.uint8)
    img[..., 0] = lab & 255
    img[..., 1] = lab >> 8
    img[..., 3] = 255
    Image.fromarray(img, "RGBA").save(f"public/brand/{name}-ids.png", optimize=True)
    cy, cx = zip(*ndimage.center_of_mass(np.ones_like(a), lab, range(1, n + 1)))
    area = ndimage.sum(np.ones_like(a), lab, range(1, n + 1))
    # Rocks cut by the image border stay put (moving one would show the cut).
    objs = ndimage.find_objects(lab)
    H, W = lab.shape
    edge = [int(sl[0].start == 0 or sl[1].start == 0 or sl[0].stop == H or sl[1].stop == W) for sl in objs]
    # Per rock: centre x, y, radius, edge flags (1 left, 2 right, 4 top, 8 bottom).
    def flags(sl):
        return (sl[1].start == 0) * 1 + (sl[1].stop == W) * 2 + (sl[0].start == 0) * 4 + (sl[0].stop == H) * 8
    rocks = [[round(x, 1), round(y, 1), round(float(np.sqrt(s / np.pi)), 1), int(flags(sl))] for x, y, s, sl in zip(cx, cy, area, objs)]
    # Centre map: each pixel of a rock holds its rock's centre (R = x/W, G = y/H,
    # 8-bit) and B = flags: bit 0 may move; bits 1-4 touches left/right/top/bottom
    # border; bits 5-7 size class (0-7, for mass).
    lut = np.zeros((n + 1, 3), dtype=np.uint8)
    for i, (x, y, sl, s) in enumerate(zip(cx, cy, objs, area), start=1):
        left, right = sl[1].start == 0, sl[1].stop == W
        top, bottom = sl[0].start == 0, sl[0].stop == H
        touches = left or right or top or bottom
        # Front rocks may move (only outward past the edges they are cut by, so the
        # cut never shows); middle-layer rocks cut by the border stay put.
        movable = key == "near" or not touches
        size = min(7, int(np.sqrt(s / np.pi) / 12))
        flags = int(movable) | (int(left) << 1) | (int(right) << 2) | (int(top) << 3) | (int(bottom) << 4) | (size << 5)
        lut[i] = [round(x / (W - 1) * 255), round(y / (H - 1) * 255), flags]
    cent = lut[lab]
    Image.fromarray(cent, "RGB").save(f"public/brand/{name}-centres.png", optimize=True)
    out[key] = {"w": int(a.shape[1]), "h": int(a.shape[0]), "rocks": rocks}
    print(key, n, "rocks")

with open("src/components/home/rocks.ts", "w") as f:
    f.write("// Generated by scripts/build-rock-ids.py. Do not edit by hand.\n")
    f.write("// Per layer: source size and each rock's [centreX, centreY, radius, edgeFlags (1 left, 2 right, 4 top, 8 bottom)] in source px (id = index + 1).\n")
    f.write("export const ROCKS = " + json.dumps(out, separators=(",", ":")) + " as const;\n")
