#!/usr/bin/env python3
"""Split the hero's meteor layers into individual rocks (for the pointer physics).

For each layer image in public/brand/, writes:
  public/brand/<name>-ids.png   rock ID per pixel (R = id & 255, G = id >> 8; 0 = none)
and src/components/home/rocks.ts with each rock's centre and radius (source px).

Rocks are connected shapes in the alpha channel; each label is grown into the
soft fringe so a moved rock takes its edge with it.
Requires numpy, scipy and Pillow:  python3 scripts/build-rock-ids.py
"""
import json
import numpy as np
from PIL import Image
from scipy import ndimage

LAYERS = {"far": "meteors-far", "near": "meteors-near"}
out = {}
for key, name in LAYERS.items():
    rgba = np.asarray(Image.open(f"public/brand/{name}.webp").convert("RGBA"))
    a = rgba[..., 3]
    lab, count = ndimage.label(a > 25)
    sizes = ndimage.sum(np.ones_like(a), lab, range(1, count + 1))
    keep = np.zeros(count + 1, dtype=bool)
    keep[1:] = sizes >= 6
    lab = np.where(keep[lab], lab, 0)
    # Renumber 1..n
    ids = np.unique(lab[lab > 0])
    remap = np.zeros(count + 1, dtype=np.int32)
    remap[ids] = np.arange(1, len(ids) + 1)
    lab = remap[lab]
    # Grow labels into the soft fringe (alpha > 3, within 4 px).
    dist, (iy, ix) = ndimage.distance_transform_edt(lab == 0, return_indices=True)
    grown = lab[iy, ix]
    lab = np.where((lab == 0) & (a > 0) & (dist <= 7), grown, lab)
    n = int(lab.max())
    img = np.zeros((*lab.shape, 4), dtype=np.uint8)
    img[..., 0] = lab & 255
    img[..., 1] = lab >> 8
    img[..., 3] = 255
    Image.fromarray(img, "RGBA").save(f"public/brand/{name}-ids.png", optimize=True)
    cy, cx = zip(*ndimage.center_of_mass(np.ones_like(a), lab, range(1, n + 1)))
    area = ndimage.sum(np.ones_like(a), lab, range(1, n + 1))
    # Rocks cut by the image border stay put (moving one would show the cut).
    objs = ndimage.find_objects(lab)
    H, W = lab.shape
    edge = [int(sl[0].start == 0 or sl[1].start == 0 or sl[0].stop == H or sl[1].stop == W) for sl in objs]
    rocks = [[round(x, 1), round(y, 1), round(float(np.sqrt(s / np.pi)), 1), e] for x, y, s, e in zip(cx, cy, area, edge)]
    out[key] = {"w": int(a.shape[1]), "h": int(a.shape[0]), "rocks": rocks}
    print(key, n, "rocks")

with open("src/components/home/rocks.ts", "w") as f:
    f.write("// Generated by scripts/build-rock-ids.py. Do not edit by hand.\n")
    f.write("// Per layer: source size and each rock's [centreX, centreY, radius, touchesEdge] in source px (id = index + 1).\n")
    f.write("export const ROCKS = " + json.dumps(out, separators=(",", ":")) + " as const;\n")
