"""Builds the Tide mark as SVG path data (traced from the supplied logo art).

Writes src/components/shell/tideMarkPaths.ts. The mark: a vertical meridian
with a bead at each end, a ring on its upper half, and two widening crescents
opening upward below it (slightly elliptical, tapering to fine tips).
"""
import math, pathlib

CX = 287.0           # meridian x (viewBox 0 0 574 954)
OY = 150.0           # artwork y offset (traced from a 1254 px source)
LINE_W = 6.6
RING = dict(cy=476.3 - OY, r=142.8, w=6.6)
BEADS = [(175.5 - OY, 15.6), (1077.5 - OY, 15.6)]
# Crescents: ellipse centre y, radii, tip height (source px), max stroke.
ARCS = [
    dict(cy=549.3 - OY, rx=213.3, ry=206.5, tip=490.5 - OY, w=8.6),
    dict(cy=678.0 - OY, rx=273.0, ry=255.0, tip=624.5 - OY, w=8.8),
]

def f(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")

def crescent(cy, rx, ry, tip, w):
    # Parameter t: angle on the ellipse, from the left tip round the bottom to the right tip.
    t0 = math.asin(max(-1, min(1, (tip - cy) / ry)))  # negative: above centre
    a0 = math.pi + t0      # left tip (x < cx)
    a1 = 2 * math.pi - t0  # right tip
    n = 90
    outer, inner = [], []
    for i in range(n + 1):
        u = i / n
        a = a0 + (a1 - a0) * u
        # y grows downward: angle measured so sin>0 is below the centre.
        x, y = CX + rx * math.cos(a), cy - ry * math.sin(a)
        nx, ny = math.cos(a) / rx, -math.sin(a) / ry
        l = math.hypot(nx, ny)
        nx, ny = nx / l, ny / l
        # Taper: full width through the bowl, fine points at the tips.
        e = min(u, 1 - u) / 0.14
        half = 0.5 * w * (0.18 + 0.82 * min(1, e) ** 0.8) * (0.8 + 0.2 * math.sin(math.pi * u))
        outer.append((x + nx * half, y + ny * half))
        inner.append((x - nx * half, y - ny * half))
    pts = outer + inner[::-1]
    return "M" + " L".join(f"{f(px)} {f(py)}" for px, py in pts) + "Z"

arcs = [crescent(**a) for a in ARCS]
out = pathlib.Path(__file__).resolve().parents[1] / "src/components/shell/tideMarkPaths.ts"
out.write_text(
    "// Generated by scripts/build-tide-mark.py (do not edit by hand).\n"
    "export const TIDE_MARK = {\n"
    f"  viewBox: \"0 0 574 954\",\n"
    f"  cx: {f(CX)},\n"
    f"  line: {{ y1: {f(BEADS[0][0])}, y2: {f(BEADS[1][0])}, w: {f(LINE_W)} }},\n"
    f"  ring: {{ cy: {f(RING['cy'])}, r: {f(RING['r'])}, w: {f(RING['w'])} }},\n"
    f"  beads: [{', '.join(f'{{ cy: {f(cy)}, r: {f(r)} }}' for cy, r in BEADS)}],\n"
    f"  arcs: [\n" + "".join(f"    \"{d}\",\n" for d in arcs) + "  ],\n"
    "} as const;\n"
)
print("wrote", out)
