"""Cuts the drifting objects out of art/drifters-sheet.webp (transparent sheet).

Writes public/brand/drifters/<name>.webp (max 320 px, alpha) and
src/components/home/drifters.ts (sizes and kinds for the hero).
"""
import json, pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
SHEET = ROOT / "art/drifters-sheet.webp"
OUT = ROOT / "public/brand/drifters"
# name, kind, box (x0, y0, x1, y1) on the sheet
ITEMS = [
    ("relay", "relay", (0, 26, 256, 262)),
    ("ring-station", "station", (271, 29, 571, 267)),
    ("dish-probe", "probe", (569, 25, 843, 279)),
    ("needle", "needle", (936, 0, 1047, 285)),
    ("sputnik", "probe", (1144, 35, 1402, 291)),
    ("asteroid", "rock", (9, 317, 264, 541)),
    ("rock-cluster", "debris", (285, 293, 571, 561)),
    ("shard", "rock", (596, 299, 827, 554)),
    ("crystal-shard", "crystal", (910, 282, 1078, 576)),
    ("debris-cluster", "debris", (1134, 310, 1396, 550)),
    ("beacon", "beacon", (555, 552, 847, 824)),
    ("cross-beacon", "beacon", (555, 824, 847, 1106)),
    ("crystal", "crystal", (905, 559, 1087, 825)),
    ("needle-2", "needle", (905, 825, 1087, 1122)),
    ("orb", "orb", (1123, 559, 1402, 829)),
    ("sphere-station", "station", (50, 819, 235, 1114)),
    ("broken-ring", "wreck", (271, 839, 568, 1105)),
    ("wreck", "wreck", (1098, 854, 1401, 1094)),
]

sheet = Image.open(SHEET).convert("RGBA")
OUT.mkdir(parents=True, exist_ok=True)
meta = []
for name, kind, box in ITEMS:
    im = sheet.crop(box)
    # Trim to the visible pixels (plus a small margin for soft glows).
    bb = im.getchannel("A").point(lambda v: 255 if v > 6 else 0).getbbox()
    if bb:
        pad = 4
        im = im.crop((max(0, bb[0] - pad), max(0, bb[1] - pad), min(im.width, bb[2] + pad), min(im.height, bb[3] + pad)))
    k = min(1.0, 320 / max(im.size))
    if k < 1:
        im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
    im.save(OUT / f"{name}.webp", "WEBP", quality=88, method=6)
    meta.append({"name": name, "kind": kind, "w": im.width, "h": im.height})

ts = ROOT / "src/components/home/drifters.ts"
ts.write_text(
    "// Generated by scripts/build-drifters.py (do not edit by hand).\n"
    "export type DrifterKind = " + " | ".join(sorted({json.dumps(m['kind']) for m in meta})) + ";\n"
    "export const DRIFTERS: { name: string; kind: DrifterKind; w: number; h: number }[] = "
    + json.dumps(meta, indent=2).replace('"name"', "name").replace('"kind"', "kind").replace('"w"', "w").replace('"h"', "h")
    + ";\n"
)
print(len(meta), "sprites")
