"""Cuts the Tide's alphabet out of art/alphabet.png (white glyphs, transparent).

Each character has two forms: the geometric "meridian" glyph (left) and the
flowing crescent glyph (right). Writes public/brand/glyphs/<char>-<form>.webp
(alpha masks, 64 px tall) and src/components/glyphs/alphabet.ts (aspects).
"""
import pathlib
import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
src = Image.open(ROOT / "art/alphabet.png").convert("RGBA")
alpha = np.array(src)[..., 3]
OUT = ROOT / "public/brand/glyphs"
OUT.mkdir(parents=True, exist_ok=True)

# Rows: characters, label centre x (from the sheet), glyph band y range.
ROWS = [
    ("ABCDEF", [102, 313, 513, 734, 942, 1151], (70, 240)),
    ("GHIJKL", [102, 312, 513, 732, 944, 1151], (286, 445)),
    ("MNOPQR", [102, 314, 515, 732, 940, 1150], (490, 662)),
    ("STUVWX", [103, 312, 515, 736, 941, 1150], (702, 862)),
    ("YZ12345", [105, 307, 476, 630, 802, 970, 1153], (904, 1062)),
    ("6789", [246, 437, 627, 819], (1100, 1240)),
]
# "10" is the fifth cell of the last row; stored under the key "0" (ten).
ROWS[-1] = ("67890", [246, 437, 627, 819, 1009], (1100, 1240))

# Erase the small label letters above each pair (they overlap the glyph bands).
LABEL_ROWS = [(41, 81), (250, 290), (460, 505), (671, 711), (874, 914), (1070, 1109)]
alpha = alpha.copy()
for (chars, xs, _), (ly0, ly1) in zip(ROWS, LABEL_ROWS):
    for x in xs:
        alpha[ly0 - 2 : ly1 + 2, x - 24 : x + 24] = 0

# Assign whole connected shapes (not rectangles) to glyphs, by each shape's
# centre: a crop never picks up slivers of a neighbouring glyph. A shape that
# spans both forms of a pair is split at the pair's centre line.
from scipy import ndimage as nd
lab, _ = nd.label(nd.binary_dilation(alpha > 24, iterations=2))
boxes = nd.find_objects(lab)

meta = {}
for chars, xs, (y0, y1) in ROWS:
    bounds = [0] + [(a + b) // 2 for a, b in zip(xs, xs[1:])] + [alpha.shape[1]]
    for k, ch in enumerate(chars):
        # The shapes in this cell (by centre).
        parts = []
        for i, sl in enumerate(boxes):
            if sl is None:
                continue
            ys_, xs_ = sl
            cy, cx = (ys_.start + ys_.stop) / 2, (xs_.start + xs_.stop) / 2
            if y0 <= cy < y1 and bounds[k] <= cx < bounds[k + 1]:
                parts.append((i, sl))
        # Split the pair at the widest empty gap in the cell's column profile
        # near its middle (the label above is not always centred on the gap).
        cell = np.zeros(alpha.shape[1], dtype=float)
        for i, sl in parts:
            cell[sl[1]] += (lab[sl] == i + 1).sum(axis=0)
        lo, hi = xs[k] - 45, xs[k] + 30
        best, split, run = -1, xs[k], 0
        for x in range(lo, hi):
            run = run + 1 if cell[x] == 0 else 0
            if run > best:
                best, split = run, x - run // 2
        if best <= 0:
            # Touching pair: cut at the thinnest column instead.
            split = lo + int(np.argmin(cell[lo:hi]))
        for form in ("a", "b"):
            keep = np.zeros_like(alpha, dtype=bool)
            for i, sl in parts:
                part = lab[sl] == i + 1
                ys_, xs_ = sl
                if xs_.start < split - 2 and xs_.stop > split + 2:
                    m = np.zeros_like(alpha, dtype=bool)
                    m[sl] = part
                    if form == "a":
                        m[:, split:] = False
                    else:
                        m[:, :split] = False
                    keep |= m
                elif ((xs_.start + xs_.stop) / 2 < split) == (form == "a"):
                    keep[sl] |= part
            a = np.where(keep, alpha, 0).astype(np.uint8)
            ys, xs2 = np.nonzero(a > 40)
            if len(ys) == 0:
                raise SystemExit(f"empty glyph {ch}{form}")
            pad = 3
            bx0, bx1, by0, by1 = xs2.min() - pad, xs2.max() + 1 + pad, ys.min() - pad, ys.max() + 1 + pad
            mask = Image.fromarray(a[by0:by1, bx0:bx1])
            white = Image.new("RGBA", mask.size, (255, 255, 255, 0))
            white.putalpha(mask)
            h = 64
            w = max(1, round(white.width * h / white.height))
            white = white.resize((w, h), Image.LANCZOS)
            name = f"{ch.lower()}-{form}"
            white.save(OUT / f"{name}.webp", "WEBP", quality=90, method=6)
            meta[name] = round(w / h, 3)

ts = ROOT / "src/components/glyphs/alphabet.ts"
ts.write_text(
    "// Generated by scripts/build-glyphs.py (do not edit by hand).\n"
    "// Width / height of each glyph; \"a\" = geometric form, \"b\" = flowing form. \"0\" is ten.\n"
    "export const GLYPH_ASPECT: Record<string, number> = {\n"
    + "".join(f'  "{k}": {v},\n' for k, v in sorted(meta.items()))
    + "};\n"
)
print(len(meta), "glyphs")
